Vagrant.configure("2") do |config|

  config.vm.define "web1" do |web1|
    web1.vm.box = "generic/ubuntu2204"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.56.11"
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "generic/ubuntu2204"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.56.12"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "generic/ubuntu2204"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.13"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

end
